{% set version = "1.44-9" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-qtl
  version: {{ version|replace("-", "_") }}

source:
  fn: qtl_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/qtl_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/qtl/qtl_{{ version }}.tar.gz

  sha256: 315063f0c3fbb95cd2169eb4109ade0339e8f3c28670b38c3167214b9bdf950e

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{compiler('c')}}    # [not win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('qtl')"  # [not win]
    - "\"%R%\" -e \"library('qtl')\""  # [win]

about:
  home: https://cran.r-project.org/web/packages/qtl/index.html
  license: GPL-3
  summary: |
    Analysis of experimental crosses to identify genes (called quantitative trait loci,
    QTLs) contributing to variation in quantitative traits.
  license_family: GPL3
extra:
   recipe-maintainers:
    - dpryan79
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
    - Johanneskoester
    - Bgruening
    - Daler
    - Jdblischak
