appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: umrelCoeSHVmW53LhjwumwRQYUFto31cznp15XsABIvz+MBa9+OEPxuiEggMHgaRWELdU8M4HBz7SceQsQ6ml9IbW1y64Ljqd67MFXozNNtmEjS8PCd67K7CM6yubBatbkb/jGYVUyGfna5FkJN2rpixwcFJrlQDsjF1mB5n28H7FdYxlHfNJCfb1Q9A70WBl2K+sPLmDhMK9d33ltDlUgY8yefoJQpVTgIsiDJaiXJ/I5jIjuQqnKmYZ4MD8rr2DABAM9D5T45uC9k7x+7awL1ZH1e4bjPAIhVIjBGsCovJ5hhz1RlcTgyuSR8OBg1GZNpz41BDYHbjRuhgC2pGjTvjWPYUmFwH19V0iQDLHRx3Cfl6W2cm+u1vrAS9tdkvg61EzWgbZ1yVoEUxmqHHdhksGWhLVYxocwGIVfPCULwrNmjeu65oLLzYxPfEbTNTT1msTBMweetX220cBYroSf6nk2i7qCo/j9wQL6r2ZnMutIDNxKktM1Noqswtcqu8nitLnf2YAj9M9GdXgDE00Ylrs/l61H1Ja4+dfl44ZdWloC4od86y0aZlI19u+biEONcFrmchA3ai5RibwHKh1hWizH06H+Mt3qEbXqSJLx5KY7iC2RUU+JhzMobobt2lkwRd2wAMRnir79N5VS5ET8qGMbGp0lk402/eARkEZ+I=}
