travis:
  secure:
    BINSTAR_TOKEN: FRUCeyP0R9rETwORORsXU9Y4vWujl/ukBq8pFYYlxd9+IE3kiRmcUGgDABL87LFBvnnKJrgZ960YHXZ5pkdaDxq5tUyL73U5ePw9D7a3Nhp9etBsiq8s4TphpwxQt0nLhP33+iePXlO0Riqc3CQRx+AKYpDOb/YqNhnKR+sVcg2xmS5q2MeO/cIF8ze/h5f6q3M/9OHemI1hSkspdS9QgoKOLogiqVcDFAuiTNWsbF5ruqZFhw/LsCjuW650K4dlum3OUUzbyrVEL7Ajy4+sY6FWRBXze2WsXXyw6o4QLyIrZm6uc9GwSXboHnrlb53/fMspADAV/qNTy6TM9Oprku20g4ddwh+KAG1UyPvCBV5wPVPoprIjqp0oVIzwGF/tIgTiPpdICd49vGy6ohQQoKX0lbfjscoTkJoj2+oZWWnCAtqfD/Qzf5Qtay2PuwrEjGRXXI+U+rLBzw477cewBFxT+oiJRN9jIIAgXkIISauXDYj3NLKSKjv9/DpFu9R1/sGyWKUAy8GHLd6xDBz4IKKwu+Dua05yhn2q2jhHLZ/gTUuh1SUqG9UlZp0RbM/0DErfwmjbYyvta77ZMr7C6ZGVq+iInlrzje2O5RF2mszjqfkUV4XLQ2etuHXuTmR0v0eHHG5ZW/FFv5p0Ba2RxIW6fitvIn30FunjmwmH51A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
