travis:
  secure:
    BINSTAR_TOKEN: nIGfi+Vy5TiF4dU9TwC7G0wiwzWtgi5Q8OvDkZYNFW6YFOVBlSUBlLk80kEm0GMXGhtDDJweNw4axurzr0fxIYNo1yVP4d8cHU9ZCLDAChL3gSAn5xphnPBsOi4uVG6JKbzahLxwrC37JRH5AFkVjKIiP+NUqe60+bbobMr5ZiIAQV+fTq5wJCcIdWsjA/6WhNNc52KC1gA4shFaz52yB56OfCjjaeqwfVnaO8uTAxOjdF5ZXy0SZyz3KMjwyWOnhEDZpAqeIpDySrh1hjZ2Sq9Q6aEwxDNKym8kfyLFC22GFjTZBk6/Kl7tws154ECfEXGnMoi7Z2Tm8eIt1TqPlBOi6ANo4HxPJ4Tl9nS2o5NneEUjyNBlSeJGvV8AV9PzsPlRD847HE2qehCpae5tWBCXft9lF+wzbkPsFh9nMiaQ8HykhwbD08b9M7/g+IWIIE96ijVpsYB8E19Xw4Nu5AwJovIzBPnWRwsxJLT1OJeKOnzsfDPejHsmGmoGtGN8nqG0L7rmPTvnhUMU1sa90784qyZMTpQnxpzpN0kUeBJDCzIwVFPacYWCbtUn8b38fS6ZQN8hp0gcCUK+WivJ3yRw6UhcvXfGWefnxA4KPDUtQ+aQ1HhnWrrqe5Ua8hmgfF79Z+sCOm4YPUGdCpIoKtwIcglgDA7GyJkZRO5qtmo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
